class Residuos {
  static final List<Map<String, dynamic>> lista = [
    {'imagen': 'assets/images/miniJuego/animatedBottle.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/can.png', 'tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/plastic_cup_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/plastic_bottle2.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/pajilla_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/aceite_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/coca_cola_bottle_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/heinz_plastic_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/pepsi_bottle_mod.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/bolsa.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/coca_cola_lata_roja.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/coca_cola_lata.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/lata_aluminio.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/lata_cerveza.png','tipo': 'plastico'},
    {'imagen': 'assets/images/miniJuego/lata_conserva.png','tipo': 'plastico'},

    {'imagen': 'assets/images/miniJuego/glass_cup.png','tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/glassBottle.png', 'tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/cerveza_vidrio.png','tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/coca_cola_vidrio.png', 'tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/wine_bottle2.png','tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/botella_mermelada.png', 'tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/botella_vidrio.png', 'tipo': 'vidrio'},
    {'imagen': 'assets/images/miniJuego/Green-Glass-Bottle.png', 'tipo': 'vidrio'},

    {'imagen': 'assets/images/miniJuego/animado_carton.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/caja_carton.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/tubo_carton.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/cajita_carton.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/caja_de_carton.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/sticky_note.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/papel_arrugado.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/papel_rayado.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/periodico.png','tipo': 'papel'},
    {'imagen': 'assets/images/miniJuego/papel_cuad.png','tipo': 'papel'},

    {'imagen': 'assets/images/miniJuego/banana.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/naranja.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/tomate.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/lechuga.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/pera.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/cebolla.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/huevo.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/apple.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/locote.png','tipo': 'organico'},
    {'imagen': 'assets/images/miniJuego/zanahoria.png','tipo': 'organico'},
    
    {'imagen': 'assets/images/miniJuego/cellphone.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/mouse.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/pila.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/teclado.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/bateria_telefono.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/calculadora.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/disco_duro.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/memoria.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/card.png','tipo': 'peligrosos'},
    {'imagen': 'assets/images/miniJuego/joystick.png','tipo': 'peligrosos'},
    
  ];
}