// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJKftiqzkQ5XZKkiJoS8oBtKyA8fzDBY',
    appId: '1:447853699292:web:fedd92b7917e29a1795419',
    messagingSenderId: '447853699292',
    projectId: 'tcc-recicla',
    authDomain: 'tcc-recicla.firebaseapp.com',
    databaseURL: 'https://tcc-recicla-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-recicla.appspot.com',
    measurementId: 'G-4X8VZ60RKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGOLrQIN3Kfuy7nYsijdLvBgdVl7zqNs',
    appId: '1:447853699292:android:3a7b696cbba4fe77795419',
    messagingSenderId: '447853699292',
    projectId: 'tcc-recicla',
    databaseURL: 'https://tcc-recicla-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-recicla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_yy0F3ihh-VbhDct1Jb5TxFxfzhGtkc',
    appId: '1:447853699292:ios:1b1e32c39e3614de795419',
    messagingSenderId: '447853699292',
    projectId: 'tcc-recicla',
    databaseURL: 'https://tcc-recicla-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-recicla.appspot.com',
    iosBundleId: 'com.example.recilaMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH_yy0F3ihh-VbhDct1Jb5TxFxfzhGtkc',
    appId: '1:447853699292:ios:1b1e32c39e3614de795419',
    messagingSenderId: '447853699292',
    projectId: 'tcc-recicla',
    databaseURL: 'https://tcc-recicla-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-recicla.appspot.com',
    iosBundleId: 'com.example.recilaMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJKftiqzkQ5XZKkiJoS8oBtKyA8fzDBY',
    appId: '1:447853699292:web:4cb4ed5e7db08a63795419',
    messagingSenderId: '447853699292',
    projectId: 'tcc-recicla',
    authDomain: 'tcc-recicla.firebaseapp.com',
    databaseURL: 'https://tcc-recicla-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-recicla.appspot.com',
    measurementId: 'G-KPND24KNM1',
  );
}
